name: 'Team labeler action'
description: "Add a team label based on the author's team"
author: '@JulienKode'
inputs:
  repo-token:
    required: true
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the label configurations'
    required: false
    default: '.github/teams.yml'
  teams-repo:
    description: 'Get the teams config from another repo'
    required: false
    default: ''
  teams-branch:
    description: 'To get the teams config from another repo, specify the branch'
    required: false
    default: ''
outputs:
  team_labels:
    description: 'JSON array of team labels for the author'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'users'
  color: 'blue'
