name: 'Team labeler action'
description: "Add a team label based on the author's team"
author: 'Julien Karst'
inputs:
  repo-token:
    required: true
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the label configurations'
    required: false
    default: '.github/teams.yml'
  source:
    required: false
    description: remote or local repository
    default: 'local'
  repo:
    required: false
    description: if source is remote, share the repository name
  owner:
    required: false
    description: if source is remote, share owner of the repo
  ref:
    required: false
    description: if source is remot, share the repository ref
    default: 'main'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'users'
  color: 'blue'
