on:
  pull_request:
  issues:
name: team-label
permissions:
  contents: read
  pull-requests: write
jobs:
  team-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"